#!/bin/bash

# -s        =>  create standalone file (in this case report.tex latex file)
# --toc     =>  create table of contents
# --natbib  =>  use the natbib package in latex
# -o        =>  output file name

pandoc midterm.md -s -o midterm.tex

pdflatex midterm.tex
bibtex midterm.aux
pdflatex midterm.tex
pdflatex midterm.tex
rm -f midterm.{log,aux,nav,out,snm,toc,blg,bbl}
rm -f midterm.tex

