#!/bin/bash

# -s        =>  create standalone file (in this case report.tex latex file)
# --toc     =>  create table of contents
# --natbib  =>  use the natbib package in latex
# -o        =>  output file name

pandoc ts_final.md -s -o ts_final.tex

pdflatex ts_final.tex
bibtex ts_final.aux
pdflatex ts_final.tex
pdflatex ts_final.tex
rm -f *.{log,aux,nav,out,snm,toc,blg,bbl}
rm -f ts_final.tex

